# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20190223_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcredentialsinfo',
            name='civilstatus',
        ),
    ]
