# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProtection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_insurance', models.BooleanField(default=False, verbose_name='\xbfCuentas con un seguro m\xe9dico de gastos mayores?')),
                ('home_insurance', models.BooleanField(default=False, verbose_name='\xbfTienes asegurada tu vivienda ante desastres naturales?')),
                ('monthly_savings', models.BooleanField(default=False, verbose_name='\xbfAhorras mensualmente para tu retiro en una Afore?')),
                ('monthly_savings_amount', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='% de ahorro')),
                ('have_credit_cards', models.BooleanField(default=False, verbose_name='\xbfTienes tarjetas de cr\xe9dito? ')),
                ('quota_available', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cupo disponible en total')),
                ('investments_assets', models.BooleanField(default=False, verbose_name='\xbfCuentas con inversiones o activos financieros que te generen beneficios?')),
                ('value_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de la inversi\xf3n con la que cuenta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_protection', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'db_table': 'personal protection',
                'verbose_name': 'Protecci\xf3n personal',
            },
        ),
    ]
